### ISSUE TITLE
Abrupt daemon termination

### ISSUE THREAD

**Issue by Kreon1987** [fhem/fhem-docker#23]
a few days ago the file "entry.sh" was changed.

now fhem is constantly restarting with the message "Abrupt daemon termination".

if I change line 535 from "export PERL_JSON_BACKEND= ..." to "PERL_JSON_BACKEND= ..." everything will work.

Everything works without change in a second fhem container.

what could that be?

**Comment by jpawlowski** [comment]
It might be a module that uses JSON and running mad due to programming issues.

If you are unable to identify any particular module, you may set the very same environment variable `PERL_JSON_BACKEND` you mentioned above to find the JSON variant still working for your setup.

I never saw any issues but potentially there is something special for you, hindering Cpanel::JSON::XS to work properly.

**Comment by Kreon1987** [comment]
ich habe das fehlerhafte modul gefunden. es ist das 70_PHTV.pm.
nachdem ich das gerät gelöscht habe, startet fhem ohne probleme.

danke für die hilfe
