### ISSUE TITLE
Update speedtest-cli: Buggy version is installed 

### ISSUE THREAD

**Issue by timomal** [fhem/fhem-docker#25]
Hello,

in the container, the installed speedtest-cli version (2.0.2) includes a bug that the measured upload-speed is wrong (too low).
Here, the bug is described: [Github: sivel/speedtest-cli/issues/575](https://github.com/sivel/speedtest-cli/issues/575 )
The current version is 2.**1**.2.

Exec inside the container and check the speedtest-cli version and measured uplink speed by:
`docker exec -ti fhem_fhem_1 speedtest-cli --version`
`docker exec -ti fhem_fhem_1 speedtest-cli`

The buggy version of speedtest-cli is included in the debian repos for over **1,5** years.

A better way to install the speedtest-cli is  by installing it directly from the git repo or via pip: 

- Via pip: `pip install speedtest-cli`
- Directly via : `git clone https://github.com/sivel/speedtest-cli.git && cd speedtest-cli && python setup.py install`

**Comment by lindhe** [comment]
AFAIK, 2.1.2 also has the bug. Or at least, it's reporting 4.10 Mbit/s for me instead of 100 which it is with other measurements.

**Comment by jpawlowski** [comment]
Installing speedtest-cli from its original source once was part of the image. However, it turned out to be unstable for a reason I don't remember right now. This is the reason it was reverted to be installed from Debian original sources.

Referring to #28, build stability might change and it might be worth looking into this once again. However, setup would look a bit different as a simple raw file download would to as well ;-)
